### ISSUE TITLE
gentxs should be collected in genesis file

### ISSUE THREAD

**Issue by OmniaFlux** [celestiaorg/devrel-tools#1]
There are some commands to generate gentx in the script like `./gmd gentx $KEY_NAME $STAKING_AMOUNT --chain-id $CHAIN_ID --keyring-backend test`, and some cosmos versions may need to run something like` ./gmd collect-gentxs` to add gentx to the genesis file to take effect.

**Comment by tzdybal** [comment]
Same thing for wordle.

CC: @YazzyYaz @jcstein

**Comment by jcstein** [comment]
resolved in https://github.com/celestiaorg/devrel-tools/pull/5!
