### ISSUE TITLE
wordle: invalid directory is removed

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/devrel-tools#4]
`init.sh` script tries to remove `.wordled` but the name of directory is `.wordle`.

https://github.com/celestiaorg/devrel-tools/blob/22921de3444a8f6c0648b23ce844644c1c9662dd/wordle/init.sh#L15

**Comment by tzdybal** [comment]
Also, the `wordled tendermint unsafe-reset-all` makes no sense if directory is removed.

**Comment by jcstein** [comment]
I don't have a direct example, but I don't think just removing `.wordle` resolves conflicts if someone starts this project and then starts over.

**Comment by jcstein** [comment]
thank you, I added fix on `init.sh` script

**Comment by jcstein** [comment]
resolved in https://github.com/celestiaorg/devrel-tools/issues/1
